[colors.primary]
background = "#262335"
foreground = "#ffffff"

[colors.cursor]
text = "#262335"
cursor = "#ff7edb"

[colors.normal]
black = "#241b2f"
red = "#fe4450"
green = "#72f1b8"
yellow = "#fede5d"
blue = "#03edf9"
magenta = "#ff7edb"
cyan = "#36f9f6"
white = "#ffffff"

[colors.bright]
black = "#495495"
red = "#fe4450"
green = "#72f1b8"
yellow = "#fede5d"
blue = "#03edf9"
magenta = "#ff7edb"
cyan = "#36f9f6"
white = "#ffffff"
