# Used by Omakub Screensaver and Screensaver.desktop
[general]
import = [ "~/.config/alacritty/theme.toml", "~/.config/alacritty/font.toml", "~/.config/alacritty/font-size.toml", "~/.config/alacritty/shared.toml" ]

[window]
startup_mode = "Fullscreen"
decorations = "None"
padding.x = 0
padding.y = 0
